# Day 24 — Pandas Methods, Basic Data Manipulation & Loading CSV Files

### Dataset: Myntra Student Shopping Data 🛍️

In this notebook, we'll learn core Pandas concepts using a realistic dataset of online shopping orders (Myntra-style) — the kind of products students actually buy: sneakers, hoodies, backpacks, jeans, earphones, and more.

**Topics covered:**
1. Common Pandas Methods — `.head()`, `.tail()`, `.shape`, `.info()`, `.describe()`, `.columns`, `.index`, `.dtypes`
2. Basic Data Manipulation (EDA) — selecting, filtering, sorting, renaming, handling missing values
3. Loading CSV Files — `pd.read_csv()`, delimiters, `.to_csv()`

## 1. Loading CSV Files

Let's start by loading our dataset using `pd.read_csv()`. This is the most common way to bring external data into a Pandas DataFrame.

In [1]:
import pandas as pd
import numpy as np

# Basic syntax: pd.read_csv(filepath)
df = pd.read_csv("myntra_student_shopping_data.csv")
print("Data loaded successfully!")
print(type(df))

Data loaded successfully!
<class 'pandas.DataFrame'>

### Specifying file path and delimiter

By default, `pd.read_csv()` assumes the file is comma-separated (`,`). If your file uses a different delimiter (like `;` or tab `\t`), you specify it using the `sep` or `delimiter` parameter.

```python
# Example if it were semicolon-separated:
df = pd.read_csv("myntra_student_shopping_data.csv", sep=';')

# Example for tab-separated file:
df = pd.read_csv("data.tsv", delimiter='\t')

# You can also load from a specific folder path:
df = pd.read_csv("/mnt/user-data/uploads/myntra_student_shopping_data.csv")
```

Since our file is a standard CSV (comma-separated), the default works fine.

## 2. Common Pandas Methods

Now that our data is loaded, let's explore it using Pandas' built-in inspection methods.

### `.head()` and `.tail()` — viewing top/bottom rows

In [2]:
# .head() shows the first 5 rows by default
df.head()

,Order_ID,Product_ID,Product_Name,Category,Sub_Category,Brand,Price,Discount_Percent,Final_Price,Rating,Number_of_Ratings,Size,Color,Student_Discount_Applied,Payment_Mode,Order_Date,Delivery_Days,City,Return_Status
0,100204,MYN1203,Nike Sports Shoes Pro,Footwear,Sports Shoes,Nike,4002,0,4002.0,2.7,3457.0,8,Black,False,Net Banking,2025-04-19,4.0,NaN,Not Returned
1,100267,MYN1266,boAt Smart Watches Sport,Electronics,Smart Watches,boAt,5523,0,5523.0,3.8,4009.0,Free Size,Beige,False,Credit Card,2025-01-12,4.0,Hyderabad,Exchanged
2,100153,MYN1152,JBL Bluetooth Speakers Pro,Electronics,Bluetooth Speakers,JBL,1151,30,805.7,4.7,159.0,Free Size,Blue,False,Net Banking,2025-07-05,6.0,Bangalore,Returned
3,100010,MYN1009,Levis Sweatshirts Classic,Topwear,Sweatshirts,Levis,2150,30,1505.0,2.8,2691.0,XXL,Maroon,False,Debit Card,2025-01-01,6.0,Delhi,Not Returned
4,100234,MYN1233,Roadster Jackets Edition,Winterwear,Jackets,Roadster,1042,40,625.2,2.8,4667.0,XL,Navy Blue,True,Cash on Delivery,2025-05-18,4.0,Jaipur,Not Returned

In [3]:
# You can pass a number to see more/fewer rows
df.head(10)

,Order_ID,Product_ID,Product_Name,Category,Sub_Category,Brand,Price,Discount_Percent,Final_Price,Rating,Number_of_Ratings,Size,Color,Student_Discount_Applied,Payment_Mode,Order_Date,Delivery_Days,City,Return_Status
0,100204,MYN1203,Nike Sports Shoes Pro,Footwear,Sports Shoes,Nike,4002,0,4002.0,2.7,3457.0,8,Black,False,Net Banking,2025-04-19,4.0,NaN,Not Returned
1,100267,MYN1266,boAt Smart Watches Sport,Electronics,Smart Watches,boAt,5523,0,5523.0,3.8,4009.0,Free Size,Beige,False,Credit Card,2025-01-12,4.0,Hyderabad,Exchanged
2,100153,MYN1152,JBL Bluetooth Speakers Pro,Electronics,Bluetooth Speakers,JBL,1151,30,805.7,4.7,159.0,Free Size,Blue,False,Net Banking,2025-07-05,6.0,Bangalore,Returned
3,100010,MYN1009,Levis Sweatshirts Classic,Topwear,Sweatshirts,Levis,2150,30,1505.0,2.8,2691.0,XXL,Maroon,False,Debit Card,2025-01-01,6.0,Delhi,Not Returned
4,100234,MYN1233,Roadster Jackets Edition,Winterwear,Jackets,Roadster,1042,40,625.2,2.8,4667.0,XL,Navy Blue,True,Cash on Delivery,2025-05-18,4.0,Jaipur,Not Returned
5,100227,MYN1226,Woodland Sweaters Edition,Winterwear,Sweaters,Woodland,1574,0,1574.0,2.6,4999.0,XL,Maroon,False,UPI,2025-06-12,8.0,NaN,Not Returned
6,100197,MYN1196,Realme Ear Phones Edition,Electronics,Ear Phones,Realme,4101,50,2050.5,NaN,NaN,Free Size,Grey,True,Debit Card,2025-03-03,9.0,Ahmedabad,Returned
7,100110,MYN1109,Levis Trousers Pro,Bottomwear,Trousers,Levis,728,30,509.6,3.1,149.0,XXL,Beige,True,Credit Card,2025-01-11,9.0,Delhi,Not Returned
8,100006,MYN1005,Roadster Trousers Everyday,Bottomwear,Trousers,Roadster,1728,50,864.0,4.0,4912.0,S,Pink,False,Credit Card,2025-01-15,9.0,Pune,Not Returned
9,100176,MYN1175,Being Human Sweatshirts Casual,Topwear,Sweatshirts,Being Human,1350,50,675.0,3.4,1709.0,M,Red,False,Debit Card,2025-04-16,8.0,Mumbai,Not Returned

In [4]:
# .tail() shows the last rows — useful to check how data ends
df.tail(5)

,Order_ID,Product_ID,Product_Name,Category,Sub_Category,Brand,Price,Discount_Percent,Final_Price,Rating,Number_of_Ratings,Size,Color,Student_Discount_Applied,Payment_Mode,Order_Date,Delivery_Days,City,Return_Status
295,100189,MYN1188,Noise Bluetooth Speakers Everyday,Electronics,Bluetooth Speakers,Noise,2241,30,1568.7,5.0,244.0,Free Size,White,True,Net Banking,2025-01-12,8.0,Bangalore,Not Returned
296,100072,MYN1071,WROGN Belts Classic,Accessories,Belts,WROGN,1634,40,980.4,4.6,1532.0,Free Size,Beige,False,Debit Card,2025-01-18,3.0,Bangalore,Not Returned
297,100107,MYN1106,Puma Caps Edition,Accessories,Caps,Puma,740,20,592.0,2.5,2176.0,Free Size,Beige,False,Cash on Delivery,2025-03-26,3.0,Delhi,Not Returned
298,100271,MYN1270,Puma Sandals Pro,Footwear,Sandals,Puma,2634,10,2370.6,NaN,NaN,9,Maroon,False,Net Banking,2025-02-25,2.0,Lucknow,Not Returned
299,100103,MYN1102,Bata Formal Shoes Casual,Footwear,Formal Shoes,Bata,1821,50,910.5,NaN,NaN,6,Olive,False,Credit Card,2025-04-22,6.0,Hyderabad,Not Returned

### `.shape` — checking rows and columns

In [5]:
# .shape returns (rows, columns) as a tuple
print("Shape of dataset:", df.shape)
print(f"Number of rows: {df.shape[0]}")
print(f"Number of columns: {df.shape[1]}")

Shape of dataset: (300, 19)
Number of rows: 300
Number of columns: 19

### `.info()` — data summary and types

`.info()` gives us a quick summary: column names, non-null counts, and data types — extremely useful to spot missing values early.

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 19 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Order_ID                  300 non-null    int64
 1   Product_ID                300 non-null    str
 2   Product_Name              300 non-null    str
 3   Category                  300 non-null    str
 4   Sub_Category              300 non-null    str
 5   Brand                     300 non-null    str
 6   Price                     300 non-null    int64
 7   Discount_Percent          300 non-null    int64
 8   Final_Price               300 non-null    float64
 9   Rating                    261 non-null    float64
 10  Number_of_Ratings         261 non-null    float64
 11  Size                      300 non-null    str
 12  Color                     300 non-null    str
 13  Student_Discount_Applied  300 non-null    bool
 14  Payment_Mode              300 non-null    str
 15  Order_Date                300 non-null    str
 16  Delivery_Days             290 non-null    float64
 17  City                      289 non-null    str
 18  Return_Status             300 non-null    str
dtypes: bool(1), float64(4), int64(3), str(11)
memory usage: 42.6 KB

### `.describe()` — statistical summary

`.describe()` gives statistical measures (mean, std, min, max, quartiles) for **numeric columns** by default.

In [7]:
df.describe()

,Order_ID,Price,Discount_Percent,Final_Price,Rating,Number_of_Ratings,Delivery_Days
count,300.000000,300.000000,300.000000,300.000000,261.000000,261.000000,290.000000
mean,100150.500000,2282.743333,28.500000,1648.400000,3.733333,2598.559387,5.682759
std,86.746758,1048.787226,17.733158,909.218134,0.723081,1463.764252,2.231276
min,100001.000000,359.000000,0.000000,220.800000,2.500000,6.000000,2.000000
25%,100075.750000,1460.750000,20.000000,940.800000,3.100000,1356.000000,4.000000
50%,100150.500000,2185.500000,30.000000,1515.500000,3.700000,2592.000000,6.000000
75%,100225.250000,3066.250000,40.000000,2234.700000,4.300000,3866.000000,8.000000
max,100300.000000,5523.000000,60.000000,5523.000000,5.000000,4999.000000,9.000000

In [8]:
# You can also describe categorical (object) columns
df.describe(include='object')

/tmp/ipykernel_595/2607232922.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include='object')

,Product_ID,Product_Name,Category,Sub_Category,Brand,Size,Color,Payment_Mode,Order_Date,City,Return_Status
count,300,300,300,300,300,300,300,300,300,289,300
unique,300,248,7,29,25,12,10,5,155,10,3
top,MYN1203,Noise Bluetooth Speakers Everyday,Winterwear,Mufflers,Roadster,Free Size,Beige,Debit Card,2025-01-12,Hyderabad,Not Returned
freq,1,4,49,22,30,121,36,73,6,35,245

### `.columns` and `.index` — viewing column and index labels

In [9]:
print("Columns:")
print(df.columns)
print()
print("Index range:")
print(df.index)

Columns:
Index(['Order_ID', 'Product_ID', 'Product_Name', 'Category', 'Sub_Category',
       'Brand', 'Price', 'Discount_Percent', 'Final_Price', 'Rating',
       'Number_of_Ratings', 'Size', 'Color', 'Student_Discount_Applied',
       'Payment_Mode', 'Order_Date', 'Delivery_Days', 'City', 'Return_Status'],
      dtype='str')

Index range:
RangeIndex(start=0, stop=300, step=1)

### `.dtypes` — checking data types

In [10]:
df.dtypes

Order_ID                      int64
Product_ID                      str
Product_Name                    str
Category                        str
Sub_Category                    str
Brand                           str
Price                         int64
Discount_Percent              int64
Final_Price                 float64
Rating                      float64
Number_of_Ratings           float64
Size                            str
Color                           str
Student_Discount_Applied       bool
Payment_Mode                    str
Order_Date                      str
Delivery_Days               float64
City                            str
Return_Status                   str
dtype: object

> **Observation:** `Order_Date` is currently stored as an `object` (string), not a proper datetime. In a real project, we'd convert it using `pd.to_datetime(df['Order_Date'])`. Keep this in mind for later lessons!

## 3. Basic Data Manipulation (EDA)

Now let's manipulate the data — selecting, filtering, sorting, renaming, and handling missing values.

### Selecting columns (`df['col']`)

In [11]:
# Selecting a single column returns a Series
df['Product_Name'].head()

0         Nike Sports Shoes Pro
1      boAt Smart Watches Sport
2    JBL Bluetooth Speakers Pro
3     Levis Sweatshirts Classic
4      Roadster Jackets Edition
Name: Product_Name, dtype: str

In [12]:
# Selecting multiple columns returns a DataFrame (note the double brackets)
df[['Product_Name', 'Brand', 'Final_Price']].head()

                 Product_Name     Brand  Final_Price
0       Nike Sports Shoes Pro      Nike       4002.0
1    boAt Smart Watches Sport      boAt       5523.0
2  JBL Bluetooth Speakers Pro       JBL        805.7
3   Levis Sweatshirts Classic     Levis       1505.0
4    Roadster Jackets Edition  Roadster        625.2

### Selecting rows with `.loc[]` and `.iloc[]`

- `.loc[]` → label/condition-based selection
- `.iloc[]` → position/index-based selection

In [13]:
# .loc[] with row label (here index is default integer, so it behaves like position too)
df.loc[0]

Order_ID                                   100204
Product_ID                                MYN1203
Product_Name                Nike Sports Shoes Pro
Category                                 Footwear
Sub_Category                         Sports Shoes
Brand                                        Nike
Price                                        4002
Discount_Percent                                0
Final_Price                                4002.0
Rating                                        2.7
Number_of_Ratings                          3457.0
Size                                            8
Color                                       Black
Student_Discount_Applied                    False
Payment_Mode                          Net Banking
Order_Date                             2025-04-19
Delivery_Days                                 4.0
City                                          NaN
Return_Status                        Not Returned
Name: 0, dtype: object

In [14]:
# .loc[] to select specific rows AND columns
df.loc[0:4, ['Product_Name', 'Category', 'Final_Price']]

                 Product_Name     Category  Final_Price
0       Nike Sports Shoes Pro     Footwear       4002.0
1    boAt Smart Watches Sport  Electronics       5523.0
2  JBL Bluetooth Speakers Pro  Electronics        805.7
3   Levis Sweatshirts Classic      Topwear       1505.0
4    Roadster Jackets Edition   Winterwear        625.2

In [15]:
# .iloc[] selects by integer position (row 0 to 4, columns 0 to 3)
df.iloc[0:5, 0:4]

   Order_ID Product_ID                Product_Name     Category
0    100204    MYN1203       Nike Sports Shoes Pro     Footwear
1    100267    MYN1266    boAt Smart Watches Sport  Electronics
2    100153    MYN1152  JBL Bluetooth Speakers Pro  Electronics
3    100010    MYN1009   Levis Sweatshirts Classic      Topwear
4    100234    MYN1233    Roadster Jackets Edition   Winterwear

In [16]:
# .iloc[] single cell access: row 2, column 3
df.iloc[2, 3]

'Electronics'

### Filtering rows with conditions

In [17]:
# Filter: products priced above 2000
expensive_items = df[df['Price'] > 2000]
print("Number of items priced above 2000:", expensive_items.shape[0])
expensive_items.head()

Number of items priced above 2000: 169

,Order_ID,Product_ID,Product_Name,Category,Sub_Category,Brand,Price,Discount_Percent,Final_Price,Rating,Number_of_Ratings,Size,Color,Student_Discount_Applied,Payment_Mode,Order_Date,Delivery_Days,City,Return_Status
0,100204,MYN1203,Nike Sports Shoes Pro,Footwear,Sports Shoes,Nike,4002,0,4002.0,2.7,3457.0,8,Black,False,Net Banking,2025-04-19,4.0,NaN,Not Returned
1,100267,MYN1266,boAt Smart Watches Sport,Electronics,Smart Watches,boAt,5523,0,5523.0,3.8,4009.0,Free Size,Beige,False,Credit Card,2025-01-12,4.0,Hyderabad,Exchanged
3,100010,MYN1009,Levis Sweatshirts Classic,Topwear,Sweatshirts,Levis,2150,30,1505.0,2.8,2691.0,XXL,Maroon,False,Debit Card,2025-01-01,6.0,Delhi,Not Returned
6,100197,MYN1196,Realme Ear Phones Edition,Electronics,Ear Phones,Realme,4101,50,2050.5,NaN,NaN,Free Size,Grey,True,Debit Card,2025-03-03,9.0,Ahmedabad,Returned
10,100238,MYN1237,Woodland Sweaters Classic,Winterwear,Sweaters,Woodland,3313,30,2319.1,3.0,2286.0,M,Grey,False,Net Banking,2025-04-14,3.0,Ahmedabad,Not Returned

In [18]:
# Multiple conditions: Footwear category AND rating above 4
good_shoes = df[(df['Category'] == 'Footwear') & (df['Rating'] > 4)]
good_shoes[['Product_Name', 'Brand', 'Rating', 'Final_Price']].head()

                  Product_Name   Brand  Rating  Final_Price
28  Campus Sports Shoes Casual  Campus     4.1       2645.0
30    Puma Formal Shoes Casual    Puma     4.1       1950.4
51        Sparx Sandals Casual   Sparx     4.7       1405.2
56  Bata Sports Shoes Everyday    Bata     4.6       2608.8
98        Sparx Slippers Sport   Sparx     4.6        870.1

In [19]:
# Filter using .isin() — useful for multiple category matches
student_essentials = df[df['Category'].isin(['Bags', 'Footwear'])]
print("Bags & Footwear orders:", student_essentials.shape[0])
student_essentials.head()

Bags & Footwear orders: 91

,Order_ID,Product_ID,Product_Name,Category,Sub_Category,Brand,Price,Discount_Percent,Final_Price,Rating,Number_of_Ratings,Size,Color,Student_Discount_Applied,Payment_Mode,Order_Date,Delivery_Days,City,Return_Status
0,100204,MYN1203,Nike Sports Shoes Pro,Footwear,Sports Shoes,Nike,4002,0,4002.0,2.7,3457.0,8,Black,False,Net Banking,2025-04-19,4.0,NaN,Not Returned
13,100046,MYN1045,American Tourister Sling Bags Classic,Bags,Sling Bags,American Tourister,2763,60,1105.2,3.8,729.0,Free Size,Olive,False,Cash on Delivery,2025-03-27,6.0,Pune,Not Returned
18,100149,MYN1148,Wildcraft Sling Bags Pro,Bags,Sling Bags,Wildcraft,1938,60,775.2,4.1,1108.0,Free Size,Maroon,True,Cash on Delivery,2025-03-03,8.0,Chennai,Not Returned
21,100114,MYN1113,Adidas Sneakers Edition,Footwear,Sneakers,Adidas,1129,30,790.3,3.4,3116.0,7,Red,False,Debit Card,2025-07-06,4.0,Lucknow,Not Returned
22,100250,MYN1249,Wildcraft Sling Bags Classic,Bags,Sling Bags,Wildcraft,3160,40,1896.0,4.9,2947.0,Free Size,White,False,Cash on Delivery,2025-06-19,4.0,Kolkata,Not Returned

### Sorting data with `.sort_values()`

In [20]:
# Sort by Final_Price ascending (default)
df.sort_values('Final_Price').head()

,Order_ID,Product_ID,Product_Name,Category,Sub_Category,Brand,Price,Discount_Percent,Final_Price,Rating,Number_of_Ratings,Size,Color,Student_Discount_Applied,Payment_Mode,Order_Date,Delivery_Days,City,Return_Status
66,100023,MYN1022,Fastrack Sunglasses Sport,Accessories,Sunglasses,Fastrack,552,60,220.8,NaN,NaN,Free Size,Navy Blue,True,Net Banking,2025-06-02,6.0,Pune,Exchanged
141,100144,MYN1143,Levis Trousers Classic,Bottomwear,Trousers,Levis,715,60,286.0,2.9,3861.0,L,Red,False,Net Banking,2025-01-18,7.0,Bangalore,Not Returned
131,100113,MYN1112,Ray-Ban Watches Casual,Accessories,Watches,Ray-Ban,359,20,287.2,NaN,NaN,Free Size,Pink,False,Net Banking,2025-02-08,4.0,Delhi,Exchanged
241,100202,MYN1201,Levis Sweatshirts Pro,Topwear,Sweatshirts,Levis,415,20,332.0,4.8,4096.0,L,Red,False,Cash on Delivery,2025-07-07,9.0,Chennai,Not Returned
248,100252,MYN1251,H&M Sweatshirts Everyday,Topwear,Sweatshirts,H&M,684,50,342.0,NaN,NaN,M,Maroon,False,UPI,2025-02-22,4.0,Ahmedabad,Returned

In [21]:
# Sort descending — most expensive items first
df.sort_values('Final_Price', ascending=False).head()

,Order_ID,Product_ID,Product_Name,Category,Sub_Category,Brand,Price,Discount_Percent,Final_Price,Rating,Number_of_Ratings,Size,Color,Student_Discount_Applied,Payment_Mode,Order_Date,Delivery_Days,City,Return_Status
1,100267,MYN1266,boAt Smart Watches Sport,Electronics,Smart Watches,boAt,5523,0,5523.0,3.8,4009.0,Free Size,Beige,False,Credit Card,2025-01-12,4.0,Hyderabad,Exchanged
122,100185,MYN1184,Sparx Slippers Pro,Footwear,Slippers,Sparx,4618,0,4618.0,3.6,2960.0,7,Navy Blue,False,Net Banking,2025-01-12,2.0,Pune,Not Returned
99,100068,MYN1067,JBL Ear Phones Everyday,Electronics,Ear Phones,JBL,4955,10,4459.5,4.6,4700.0,Free Size,Grey,False,UPI,2025-06-19,6.0,Bangalore,Returned
179,100142,MYN1141,Puma Sandals Classic,Footwear,Sandals,Puma,4379,0,4379.0,4.5,693.0,9,Beige,False,Cash on Delivery,2025-01-24,5.0,Kolkata,Not Returned
165,100143,MYN1142,JBL Smart Watches Sport,Electronics,Smart Watches,JBL,4764,10,4287.6,3.9,1017.0,Free Size,White,False,Cash on Delivery,2025-07-07,8.0,Ahmedabad,Not Returned

In [22]:
# Sort by multiple columns: Category (A-Z), then Rating (high to low)
df.sort_values(['Category', 'Rating'], ascending=[True, False]).head(10)

,Order_ID,Product_ID,Product_Name,Category,Sub_Category,Brand,Price,Discount_Percent,Final_Price,Rating,Number_of_Ratings,Size,Color,Student_Discount_Applied,Payment_Mode,Order_Date,Delivery_Days,City,Return_Status
35,100120,MYN1119,Ray-Ban Caps Everyday,Accessories,Caps,Ray-Ban,1748,30,1223.6,5.0,4347.0,Free Size,Maroon,True,Cash on Delivery,2025-01-13,6.0,Hyderabad,Not Returned
63,100186,MYN1185,Fastrack Belts Casual,Accessories,Belts,Fastrack,3649,10,3284.1,5.0,3944.0,Free Size,Beige,False,Net Banking,2025-04-18,2.0,Lucknow,Not Returned
156,100223,MYN1222,Puma Belts Casual,Accessories,Belts,Puma,3770,30,2639.0,4.9,3697.0,Free Size,Beige,False,UPI,2025-04-04,7.0,Chennai,Returned
217,100280,MYN1279,Titan Caps Sport,Accessories,Caps,Titan,2510,60,1004.0,4.8,267.0,Free Size,Maroon,False,Debit Card,2025-02-23,6.0,Delhi,Not Returned
121,100173,MYN1172,WROGN Belts Edition,Accessories,Belts,WROGN,2965,30,2075.5,4.7,715.0,Free Size,Navy Blue,False,UPI,2025-02-20,8.0,Mumbai,Not Returned
285,100258,MYN1257,Titan Wallets Edition,Accessories,Wallets,Titan,3297,20,2637.6,4.7,3794.0,Free Size,Red,False,UPI,2025-05-25,6.0,Delhi,Not Returned
17,100212,MYN1211,Puma Caps Casual,Accessories,Caps,Puma,2782,30,1947.4,4.6,461.0,Free Size,Olive,True,Debit Card,2025-01-22,4.0,Lucknow,Not Returned
82,100020,MYN1019,Fastrack Watches Everyday,Accessories,Watches,Fastrack,3275,30,2292.5,4.6,1803.0,Free Size,Black,True,Credit Card,2025-07-04,2.0,Lucknow,Returned
296,100072,MYN1071,WROGN Belts Classic,Accessories,Belts,WROGN,1634,40,980.4,4.6,1532.0,Free Size,Beige,False,Debit Card,2025-01-18,3.0,Bangalore,Not Returned
36,100008,MYN1007,Titan Wallets Everyday,Accessories,Wallets,Titan,2867,0,2867.0,4.5,392.0,Free Size,Maroon,True,Debit Card,2025-06-12,4.0,Jaipur,Not Returned

### Renaming columns with `.rename()`

In [23]:
# Rename specific columns using a dictionary — doesn't affect original unless we reassign or use inplace=True
df_renamed = df.rename(columns={'Final_Price': 'Price_After_Discount', 'Number_of_Ratings': 'Total_Ratings'})
df_renamed.columns

Index(['Order_ID', 'Product_ID', 'Product_Name', 'Category', 'Sub_Category',
       'Brand', 'Price', 'Discount_Percent', 'Price_After_Discount', 'Rating',
       'Total_Ratings', 'Size', 'Color', 'Student_Discount_Applied',
       'Payment_Mode', 'Order_Date', 'Delivery_Days', 'City', 'Return_Status'],
      dtype='str')

### Checking for missing values (`.isnull()`, `.notnull()`)

In [24]:
# .isnull() returns True/False for each cell
df.isnull().head()

,Order_ID,Product_ID,Product_Name,Category,Sub_Category,Brand,Price,Discount_Percent,Final_Price,Rating,Number_of_Ratings,Size,Color,Student_Discount_Applied,Payment_Mode,Order_Date,Delivery_Days,City,Return_Status
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [25]:
# Much more useful: count missing values per column
df.isnull().sum()

Order_ID                     0
Product_ID                   0
Product_Name                 0
Category                     0
Sub_Category                 0
Brand                        0
Price                        0
Discount_Percent             0
Final_Price                  0
Rating                      39
Number_of_Ratings           39
Size                         0
Color                        0
Student_Discount_Applied     0
Payment_Mode                 0
Order_Date                   0
Delivery_Days               10
City                        11
Return_Status                0
dtype: int64

In [26]:
# .notnull() is the opposite — True where data EXISTS
df.notnull().sum()

Order_ID                    300
Product_ID                  300
Product_Name                300
Category                    300
Sub_Category                300
Brand                       300
Price                       300
Discount_Percent            300
Final_Price                 300
Rating                      261
Number_of_Ratings           261
Size                        300
Color                       300
Student_Discount_Applied    300
Payment_Mode                300
Order_Date                  300
Delivery_Days               290
City                        289
Return_Status               300
dtype: int64

In [27]:
# Percentage of missing values per column
(df.isnull().sum() / len(df) * 100).round(2)

Order_ID                     0.00
Product_ID                   0.00
Product_Name                 0.00
Category                     0.00
Sub_Category                 0.00
Brand                        0.00
Price                        0.00
Discount_Percent             0.00
Final_Price                  0.00
Rating                      13.00
Number_of_Ratings           13.00
Size                         0.00
Color                        0.00
Student_Discount_Applied     0.00
Payment_Mode                 0.00
Order_Date                   0.00
Delivery_Days                3.33
City                         3.67
Return_Status                0.00
dtype: float64

### Dropping missing values (`.dropna()`) and filling them (`.fillna()`)

In [28]:
# dropna() removes ANY row that has at least one missing value
df_dropped = df.dropna()
print("Original shape:", df.shape)
print("Shape after dropna():", df_dropped.shape)

Original shape: (300, 19)
Shape after dropna(): (242, 19)

In [29]:
# dropna with subset — only drop rows missing in specific important columns
df_dropped_subset = df.dropna(subset=['City'])
print("Shape after dropping rows with missing City:", df_dropped_subset.shape)

Shape after dropping rows with missing City: (289, 19)

In [30]:
# fillna() — fill missing Rating with the average rating instead of dropping data
avg_rating = df['Rating'].mean()
df_filled = df.copy()
df_filled['Rating'] = df_filled['Rating'].fillna(round(avg_rating, 1))

# fill missing City with 'Unknown'
df_filled['City'] = df_filled['City'].fillna('Unknown')

# fill missing Delivery_Days with the median delivery time
df_filled['Delivery_Days'] = df_filled['Delivery_Days'].fillna(df_filled['Delivery_Days'].median())

print("Missing values after fillna():")
df_filled.isnull().sum()

Missing values after fillna():

Order_ID                     0
Product_ID                   0
Product_Name                 0
Category                     0
Sub_Category                 0
Brand                        0
Price                        0
Discount_Percent             0
Final_Price                  0
Rating                       0
Number_of_Ratings           39
Size                         0
Color                        0
Student_Discount_Applied     0
Payment_Mode                 0
Order_Date                   0
Delivery_Days                0
City                         0
Return_Status                0
dtype: int64

> **Why `fillna()` over `dropna()` here?** Dropping rows loses valuable order data (price, brand, category etc.) just because one field like `Rating` is missing. Filling with a sensible default (mean/median/placeholder) preserves the dataset size for further analysis — a common real-world trade-off.

## 4. Saving DataFrame to CSV with `.to_csv()`

After cleaning, we usually save our processed data for future use.

In [31]:
# Save the cleaned dataset (missing values handled) to a new CSV file
df_filled.to_csv("myntra_student_shopping_data_cleaned.csv", index=False)
print("Cleaned file saved as 'myntra_student_shopping_data_cleaned.csv'")

Cleaned file saved as 'myntra_student_shopping_data_cleaned.csv'

In [32]:
# Quick verification — read it back
check_df = pd.read_csv("myntra_student_shopping_data_cleaned.csv")
check_df.isnull().sum()

Order_ID                     0
Product_ID                   0
Product_Name                 0
Category                     0
Sub_Category                 0
Brand                        0
Price                        0
Discount_Percent             0
Final_Price                  0
Rating                       0
Number_of_Ratings           39
Size                         0
Color                        0
Student_Discount_Applied     0
Payment_Mode                 0
Order_Date                   0
Delivery_Days                0
City                         0
Return_Status                0
dtype: int64

## 5. Quick Recap & Practice Exercise 📝

**What we covered today:**

| Concept | Method |
|---|---|
| View top/bottom rows | `.head()`, `.tail()` |
| Check dimensions | `.shape` |
| Data summary & types | `.info()`, `.dtypes` |
| Statistical summary | `.describe()` |
| Column/index labels | `.columns`, `.index` |
| Select column(s) | `df['col']`, `df[['col1','col2']]` |
| Select rows | `.loc[]`, `.iloc[]` |
| Filter rows | Boolean conditions, `.isin()` |
| Sort data | `.sort_values()` |
| Rename columns | `.rename()` |
| Missing values | `.isnull()`, `.notnull()` |
| Handle missing values | `.dropna()`, `.fillna()` |
| Read/Write CSV | `pd.read_csv()`, `.to_csv()` |

### 🎯 Try it yourself
1. Find all products from the brand `"Roadster"` with a discount greater than 30%.
2. Sort the dataset by `Delivery_Days` ascending — which order arrived fastest?
3. Rename `Student_Discount_Applied` to `Has_Student_Discount` and save the result to a new CSV.

In [33]:
# Space for practice — try writing your own code here!